spring:
  datasource:
    data: classpath:data-h2.sql # server 기동시 자동으로 실행될 sql 구문
  h2:
    console: # h2-console 사용
      enabled: true
      path: /h2-console
  jpa: # jpa sql 로깅
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false # lazy loading으로 인해 json serialize 오류 방지
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # eureka server 주소

swagger:
  host: localhost:8090